### ISSUE TITLE
ATTENTION Scott Madeira: Requesting new columns in database schema.

### ISSUE THREAD

**Issue by JackBrosius** [smadeira/CSC483_Content_Manager#12]
requesting the following columns:
schedules.valid -  char (5) NULL ALLOWED
presentations.valid - char (5) NULL ALLOWED
content.valid - char (5) NULL ALLOWED
schedules.use_default - char (5) NULL ALLOWED

constraints: all must = NULL, true, or false

No indexes

**Comment by JoshTG** [comment]
Questions:
- Why add the valid fields? Wouldn't that be assumed already if the schedule/presentation exists?
- Why the use_default? Wouldn't that already be assumed if no presentation is set up, just to use the default image?
- Why no indexes?

**Comment by JackBrosius** [comment]
This was my solution to a problem that Scott Madeira just said not to do.  I am assuming he is closing this ticket.
________________________________
