### ISSUE TITLE
ATTENTION Scott Madeira: Signage / Database Upgrades

### ISSUE THREAD

**Issue by JackBrosius** [smadeira/CSC483_Content_Manager#13]
Suggest Database Upgrades:
delete columns:

schedules.start_date
schedules.end_date

seems to be a repeat.

Also, suggesting following indexes:
All primary or foreign keys.

http://signage.codeflare.tech/api/televisions/1

All the null values need values.  Also, TV controllers are missing data on signage that we need.
We need the following tables up:

schedule_television
presentation_schedule
content_presentation

Also, add constraints in these 3 tables that start_date and end_date be in proper timestamp format and NOT NULL.

**Comment by smadeira** [comment]
Schedule start and end date are not redundant.  A schedule can run for multiple days with a start date/time and and end date/time.  This is useful for the presentation creator and schedule creator to see what they are creating and when it will run.

Don't worry about the keys and indexes.  I'll take care of that when I move this into production.  Small databse like this will not have performance impacts from missing indexes.

Not sure what "all the null values need values" means.  There are non-required fields where Null is a valid value.

What specific fields do you need from the intermediate tables?

**Comment by JackBrosius** [comment]
Okay, I was just seeing whether the null fields in the json were needed.  It might be impossible to use certain objects if some fields are still null (but like you said it can still at least do something.)  From the intermediate fields, we will at least need the ones dealing with time.
________________________________
