### ISSUE TITLE
Null Data On Signage / Documentation Needed

### ISSUE THREAD

**Issue by JackBrosius** [smadeira/CSC483_Content_Manager#15]
On http://signage.codeflare.tech/api/televisions/1.
There are still null values spread throughout.  There is no indication of when null values are allowed or are not allowed.  I need more information about what values are required and which are not to make the error checking utility.  I also need some documentation from Professor Madeira regarding how this information is going to actually be used (some things are intuitive, others I am confused).

**Comment by smadeira** [comment]
Not sure what you are asking for.  If you don't get enough information provided in a schedule to play the schedule and presentations on the screen then you play the default image.  If you have a schedule with multiple presentations but one isn't valid (doesn't contain enough data for you to be able to display it) then you should not run the preesentation.  You can run the other presentations in the schedule, if there are any. Net of it all, you need to take what you get and regardless of how good or bad it is, you need to display something.  The error checking you are doing is probably more like validation checking to see what you can displacy and what you can't.  You are making the TV Controller fault tolerant.  Hope that helps.
